### ISSUE TITLE
M1 Max, Mac OS Sonoma 14.2.1

### ISSUE THREAD

**Issue by x92mko** [0blu/EverlookClassicLauncher#57]
Hi there,

I have problems with the launcher. Do you have some hints to fix the launcher? 

I downloaded the WinterspringLauncher.dmg Version 2023-08-12 (v1.5.0) (https://github.com/0blu/WinterspringLauncher/releases/tag/1.5.0) because no newer version is available for Mac OS. Unfortunately, the launcher could not prepare the HermesProxy.

I am running a M1 Max, Mac OS Sonoma 14.2.1 machine. 

Thank you in advance!

Unable to patch '/Users/marco/WinterspringLauncher/hermes-proxy/CSV/Hotfix/ItemEffect1.csv' (WinterspringLauncher.HermesDataPatches.Hotfix.ItemEffect1.csv)
System.IO.DirectoryNotFoundException: Could not find a part of the path '/Users/marco/WinterspringLauncher/hermes-proxy/CSV/Hotfix/ItemEffect1.csv'.
   at Interop.ThrowExceptionForIoErrno(ErrorInfo errorInfo, String path, Boolean isDirError)
   at Microsoft.Win32.SafeHandles.SafeFileHandle.Open(String fullPath, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize, UnixFileMode openPermissions, Int64& fileLength, UnixFileMode& filePermissions, Func`4 createOpenException)
   at System.IO.Strategies.OSFileStreamStrategy..ctor(String path, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize, Nullable`1 unixCreateMode)
   at System.IO.StreamReader.ValidateArgsAndOpenPath(String path, Encoding encoding, Int32 bufferSize)
   at System.IO.File.ReadAllLines(String path, Encoding encoding)
   at WinterspringLauncher.LauncherActions.<PrepareHermesProxyData>g__PatchCsvFiles|19_2(List`1 patchResources, String replace, String csvDirPath, <>c__DisplayClass19_0&) in /Users/runner/work/WinterspringLauncher/WinterspringLauncher/WinterspringLauncher/LauncherActions.cs:line 449
   at WinterspringLauncher.LauncherActions.PrepareHermesProxyData(String hermesPath) in /Users/runner/work/WinterspringLauncher/WinterspringLauncher/WinterspringLauncher/LauncherActions.cs:line 417
   at WinterspringLauncher.Launcher.<>c__DisplayClass1_0.<Main>b__5() in /Users/runner/work/WinterspringLauncher/WinterspringLauncher/WinterspringLauncher/Program.cs:line 72
   at WinterspringLauncher.Launcher.IgnoreExceptions(String description, Action func) in /Users/runner/work/WinterspringLauncher/WinterspringLauncher/WinterspringLauncher/Program.cs:line 152
>>> Failed to prepare HermesProxy Data, continuing anyways (might not work) <<<
Unhandled exception. System.IO.FileNotFoundException: Could not find file '/Users/marco/WinterspringLauncher/hermes-proxy/HermesProxy.config'.
File name: '/Users/marco/WinterspringLauncher/hermes-proxy/HermesProxy.config'
   at Interop.ThrowExceptionForIoErrno(ErrorInfo errorInfo, String path, Boolean isDirError)
   at Microsoft.Win32.SafeHandles.SafeFileHandle.Open(String fullPath, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize, UnixFileMode openPermissions, Int64& fileLength, UnixFileMode& filePermissions, Func`4 createOpenException)
   at System.IO.Strategies.OSFileStreamStrategy..ctor(String path, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize, Nullable`1 unixCreateMode)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize)
   at System.Xml.XmlDownloadManager.GetStream(Uri uri, ICredentials credentials, IWebProxy proxy)
   at System.Xml.XmlTextReaderImpl.OpenUrl()
   at System.Xml.XmlTextReaderImpl.Read()
   at System.Xml.XmlLoader.Load(XmlDocument doc, XmlReader reader, Boolean preserveWhitespace)
   at System.Xml.XmlDocument.Load(XmlReader reader)
   at System.Xml.XmlDocument.Load(String filename)
   at WinterspringLauncher.LauncherActions.PrepareHermesProxyConfig(String hermesPath, String realmlist) in /Users/runner/work/WinterspringLauncher/WinterspringLauncher/WinterspringLauncher/LauncherActions.cs:line 481
   at WinterspringLauncher.Launcher.Main(String[] args) in /Users/runner/work/WinterspringLauncher/WinterspringLauncher/WinterspringLauncher/Program.cs:line 73
/Applications/Winterspring Launcher.app/WinterspringLauncherTerminal: line 12:  5599 Abort trap: 6           DYLD_LIBRARY_PATH="$CURRENTPATH/Libs" ./WinterspringLauncher

Saving session...
...copying shared history...
...saving history...truncating history files...
...completed.
Deleting expired sessions...       3 completed.

[Process completed]

**Comment by x92mko** [comment]
I fixed it meanwhile. I copied the missing data from the folders into the correct path!
