### ISSUE TITLE
System.Exception Unknown file format cannot decompress

### ISSUE THREAD

**Issue by nickzwaans** [0blu/EverlookClassicLauncher#65]
Fresh install of the launcher on windows, encountering a failure to decompress issue when running the download. Attached logs.
Logs:
```
Base path: "M:\Dernloois"
GitHub API Address: https://api.github.com/
Launching...
---------- Selected Server Config ----------
Name: Everlook (Europe)
Realmlist: logon.everlook.org
Game Directory: ./winterspring-data/WoW 1.14.2 Everlook
Game Version: 1.14.2.42597
--------------------------------------------
Checking WoW installation
Patched client was NOT found at "./winterspring-data/WoW 1.14.2 Everlook\_classic_era_/WowClassic_ForCustomServers.exe"
Default wow client was NOT found at "./winterspring-data/WoW 1.14.2 Everlook\_classic_era_/WowClassic.exe"
Downloading WoW Client...
Download URL: https://download.wowdl.net/downloadFiles/Clients/WoW%20Classic%201.14.2.42597%20All%20Languages.rar
Download Location: M:\Dernloois\winterspring-data\WoW 1.14.2 Everlook.partial-download
Unpack to: M:\Dernloois\winterspring-data\WoW 1.14.2 Everlook
System.AggregateException: One or more errors occurred. (Unknown file format. Cannot decompress)
 ---> System.Exception: Unknown file format. Cannot decompress
   at WinterspringLauncher.Utils.ArchiveCompression.Decompress(String archiveFilePath, String extractionFolderPath, String folderToSkipName, UnpackProgressInfoHandler progressHandler, Func`2 shouldBeDecompressedPredicate) in D:\a\WinterspringLauncher\WinterspringLauncher\WinterspringLauncher\Utils\ArchiveCompression.cs:line 35
   at WinterspringLauncher.LauncherActions.Unpack(String compressedArchivePath, String targetDir, UnpackProgressInfoHandler progressInfoHandler) in D:\a\WinterspringLauncher\WinterspringLauncher\WinterspringLauncher\LauncherActions.cs:line 89
   at WinterspringLauncher.LauncherLogic.RunUnpack(String archiveLocation, String targetDir) in D:\a\WinterspringLauncher\WinterspringLauncher\WinterspringLauncher\LauncherLogic.cs:line 153
   at WinterspringLauncher.LauncherLogic.<>c__DisplayClass14_0.<<StartGame>b__0>d.MoveNext() in D:\a\WinterspringLauncher\WinterspringLauncher\WinterspringLauncher\LauncherLogic.StartGame.cs:line 127
   --- End of inner exception stack trace --
```

**Comment by 0blu** [comment]
It seems like the URL https://download.wowdl.net/downloadFiles/Clients/WoW%20Classic%201.14.2.42597%20All%20Languages.rar does not work anymore.
Can you try to download it manually and place the file into this folder:
`M:\Dernloois\winterspring-data\WoW 1.14.2 Everlook.partial-download`
And also rename it to `WoW 1.14.2 Everlook.partial-download` mind that there is no `.rar` ending

**Comment by nickzwaans** [comment]
> It seems like the URL https://download.wowdl.net/downloadFiles/Clients/WoW%20Classic%201.14.2.42597%20All%20Languages.rar does not work anymore. Can you try to download it manually and place the file into this folder: `M:\Dernloois\winterspring-data\WoW 1.14.2 Everlook.partial-download` And also rename it to `WoW 1.14.2 Everlook.partial-download` mind that there is no `.rar` ending

This worked! I used this version https://wowdl.net/client/wow-classic-1.14.2.42597-all-languages

**Comment by Aareon** [comment]
Same issue
```
Launcher started
Base path: "G:\Downloads"
GitHub API Address: https://api.github.com/
Launching...
---------- Selected Server Config ----------
Name: Everlook (Europe)
Realmlist: logon.everlook.org
Game Directory: ./winterspring-data/WoW 1.14.2 Everlook
Game Version: 1.14.2.42597
--------------------------------------------
Checking WoW installation
Patched client was NOT found at "./winterspring-data/WoW 1.14.2 Everlook\_classic_era_/WowClassic_ForCustomServers.exe"
Default wow client was NOT found at "./winterspring-data/WoW 1.14.2 Everlook\_classic_era_/WowClassic.exe"
Downloading WoW Client...
Download URL: https://download.wowdl.net/downloadFiles/Clients/WoW%20Classic%201.14.2.42597%20All%20Languages.rar
Download Location: G:\Downloads\winterspring-data\WoW 1.14.2 Everlook.partial-download
Unpack to: G:\Downloads\winterspring-data\WoW 1.14.2 Everlook
System.AggregateException: One or more errors occurred. (Unknown file format. Cannot decompress)
 ---> System.Exception: Unknown file format. Cannot decompress
   at WinterspringLauncher.Utils.ArchiveCompression.Decompress(String archiveFilePath, String extractionFolderPath, String folderToSkipName, UnpackProgressInfoHandler progressHandler, Func`2 shouldBeDecompressedPredicate) in D:\a\WinterspringLauncher\WinterspringLauncher\WinterspringLauncher\Utils\ArchiveCompression.cs:line 35
   at WinterspringLauncher.LauncherActions.Unpack(String compressedArchivePath, String targetDir, UnpackProgressInfoHandler progressInfoHandler) in D:\a\WinterspringLauncher\WinterspringLauncher\WinterspringLauncher\LauncherActions.cs:line 89
   at WinterspringLauncher.LauncherLogic.RunUnpack(String archiveLocation, String targetDir) in D:\a\WinterspringLauncher\WinterspringLauncher\WinterspringLauncher\LauncherLogic.cs:line 153
   at WinterspringLauncher.LauncherLogic.<>c__DisplayClass14_0.<<StartGame>b__0>d.MoveNext() in D:\a\WinterspringLauncher\WinterspringLauncher\WinterspringLauncher\LauncherLogic.StartGame.cs:line 127
   --- End of inner exception stack trace ---
   ```
