### ISSUE TITLE
Mac download  failed

### ISSUE THREAD

**Issue by FLZC** [0blu/EverlookClassicLauncher#67]
BasePath: /Users/panda/WinterspringLauncher
New launcher update 1.5.0 => 2.1.0
A new version was released, please update
https://github.com/0blu/WinterspringLauncher/releases
Did not found complete 1.14 game installation
Downloading from wowdl.net: url "https://download.wowdl.net/downloadFiles/Clients/WoW_Classic_1.14.0.40618_macOS_new.zip"
Placing temporary download file alongside launcher
Download size -1.00 Byte
Download [██████████████████████████████████████████████████]  100%   Done                                       
System.IO.InvalidDataException: End of Central Directory record could not be found.
   at System.IO.Compression.ZipArchive.ReadEndOfCentralDirectory()
   at System.IO.Compression.ZipArchive..ctor(Stream stream, ZipArchiveMode mode, Boolean leaveOpen, Encoding entryNameEncoding)
   at System.IO.Compression.ZipFile.Open(String archiveFileName, ZipArchiveMode mode, Encoding entryNameEncoding)
   at WinterspringLauncher.Utils.ArchiveCompression.DecompressZipWithProgress(String archiveFilePath, String extractionFolderPath) in /Users/runner/work/WinterspringLauncher/WinterspringLauncher/WinterspringLauncher/Utils/ArchiveCompression.cs:line 26
   at WinterspringLauncher.Utils.ArchiveCompression.DecompressWithProgress(String archiveFilePath, String extractionFolderPath) in /Users/runner/work/WinterspringLauncher/WinterspringLauncher/WinterspringLauncher/Utils/ArchiveCompression.cs:line 16
   at WinterspringLauncher.LauncherActions.ExtractGameClient(String gamePath) in /Users/runner/work/WinterspringLauncher/WinterspringLauncher/WinterspringLauncher/LauncherActions.cs:line 359
   at WinterspringLauncher.Launcher.PrepareGame(UpdateApiClient api, Boolean weAreOnMacOs, String gamePath) in /Users/runner/work/WinterspringLauncher/WinterspringLauncher/WinterspringLauncher/Program.cs:line 263
   at WinterspringLauncher.Launcher.<>c__DisplayClass1_0.<Main>b__2() in /Users/runner/work/WinterspringLauncher/WinterspringLauncher/WinterspringLauncher/Program.cs:line 65
   at WinterspringLauncher.Launcher.IgnoreExceptions(String description, Action func) in /Users/runner/work/WinterspringLauncher/WinterspringLauncher/WinterspringLauncher/Program.cs:line 152
   

   
<img width="446" alt="WechatIMG406" src="https://github.com/user-attachments/assets/eb30e413-dea5-41f8-844d-8c46f3991d0d">

 **_I tried downloading it locally and running WinterspringLauncherTerminal， it didn't work_**

**Comment by 0blu** [comment]
I think you need to manually download the file

https://wowdl.net/client/World-of-Warcraft-Classic-1.14.0.40618
![image](https://github.com/user-attachments/assets/645bb2d4-88a6-4758-a242-099c31323d38)
name the file `__tmp__game-client.zip` and place it along the launcher.

(better back up this file, so if the decompression fails you still have a backup)

**Comment by HerrTiSo** [comment]
WoWDL is dead.
